# Generated by Django 4.2 on 2023-05-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
                ('proyecto', models.IntegerField(blank=True, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centros.ficha')),
                ('nombre_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grupos.grupo')),
            ],
        ),
    ]
