# Generated by Django 4.2 on 2023-05-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=5000)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='proyectos/foto')),
                ('codigo_fuente', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('terminado', 'terminado'), ('en revision', 'en revision'), ('en desarrollo', 'en desarrollo')], default='en revision', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, null=True, to='proyectos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('desaprobado', 'desaprobado')], max_length=20, null=True)),
                ('descripcion_entrega', models.CharField(max_length=5000)),
                ('respuesta_instructor', models.CharField(blank=True, max_length=5000, null=True)),
                ('instructror', models.EmailField(blank=True, max_length=254, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.inscrito')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.proyecto')),
                ('tipo_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.tipo_revision')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='proyectos/documentos')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.entrega')),
            ],
        ),
    ]
